# Uncomment the next line to define a/Users/panxuanyi/Desktop/1/xyb/maobi/NSTDemo global platform for your project
platform :ios, '13.0'

target 'NSTDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Masonry'
pod 'SnapKitExtend'

pod 'Kingfisher'
pod 'Reusable'
pod 'IBAnimatable'
pod 'ButtonProgressBar-iOS'
pod 'AttributedString'
pod 'SwiftyStarRatingView'

  # Pods for NSTDemo

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end


